name: notely
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.3
  flutter_screenutil: ^5.9.3
  icons_launcher: ^3.0.0
  shared_preferences: ^2.3.4
  very_good_analysis: ^7.0.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true

  assets:
    - assets/images/app_logo/notely_logo.png
    - assets/images/splash/
    - assets/images/

  fonts:
    - family: Titan One
      fonts:
        - asset: assets/fonts/titan_one/TitanOne-Regular.ttf

    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito/Nunito-Regular.ttf
        - asset: assets/fonts/nunito/Nunito-Medium.ttf
          weight: 600
        - asset: assets/fonts/nunito/Nunito-Bold.ttf
          weight: 900